version: '3.3'

services:

  mura:
    build:
      context: .
      # context: https://github.com/digitalminellc/mura-training.git#:mura-docker
    image: digitalmine/mura-training:latest
    depends_on:
      - svc_muradb
    environment:
      MURA_ADMIN_USERNAME: admin
      MURA_ADMIN_PASSWORD: admin
      MURA_ADMINEMAIL: steve@digitalmie.com
      MURA_APPRELOADKEY: appreload
      MURA_DATASOURCE: dsn_mura
      MURA_DATABASE: muradb
      MURA_DBTYPE: mysql
      MURA_DBUSERNAME: root
      MURA_DBPASSWORD: P@55w0rd!
      MURA_DBHOST: svc_muradb
      MURA_DBPORT: 3306
      MURA_PORT: 8008
      MURA_SITEIDINURLS: "false"
      MURA_INDEXFILEINURLS: "true"
      MURA_TESTBOX: "true"
      MURA_USESSL: "false"
      MURA_AUTODISCOVERPLUGINS: "true"
      CFCONFIG_ADMINPASSWORD: P@55w0rd!
      #LUCEE_JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - ./www/modules:/app/modules
      - ./www/plugins:/app/plugins
      - ./www/sites:/app/sites
      - ./www/themes:/app/themes
      - ./www/training:/app/training
    ports:
      - "8008:8080"
    tty: true

  # DB
  svc_muradb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: muradb
      MYSQL_ROOT_PASSWORD: P@55w0rd!
    volumes:
      - vol_muradb:/var/lib/mysql
    ports:
      - "5005:3306"

# Mounts
volumes:
  vol_muradb:
